[versions]
agp = "9.0.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
gamesActivity = "4.0.0"
openxr_loader_for_android = "1.1.54"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
openxr-loader-android = { group = "org.khronos.openxr", name = "openxr_loader_for_android", version.ref = "openxr_loader_for_android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

